# Admittance parameters for two mass damper systems
# (the arm and the platform) with params (mass_arm, damping_arm)
# and (mass_platform, damping_platform) respectively, connected by a
# spring-damper with parameters (damping_coupling, stiffness_coupling,
# equilibrium_point_spring)

mass_arm: [2,0,0,0,0,0,
           0,2,0,0,0,0,
           0,0,2,0,0,0,
           0,0,0,2,0,0,
           0,0,0,0,2,0,
           0,0,0,0,0,2]

damping_arm: [12,0,0,0,0,0,
              0,12,0,0,0,0,
              0,0,12,0,0,0,
              0,0,0,10,0,0,
              0,0,0,0,10,0,
              0,0,0,0,0,10]

stiffness_coupling: [10,0,0,0,0,0,
                     0,20,0,0,0,0,
                     0,0,10,0,0,0,
                     0,0,0,10,0,0,
                     0,0,0,0,10,0,
                     0,0,0,0,0,10]
# [position (x, y, z)  orientation (x, y, z, w)]
equilibrium_point_spring: [0.257, 0.214, 0.367, 0.5, 0.5, 0.5, -0.5]

workspace_limits: [-0.50, 0.50, -0.50, 0.50, 0.01, 0.80]

arm_max_vel: 10.5
arm_max_acc: 10.0
